os:
  - osx

language: java

jdk:
  - oraclejdk8

script: mvn clean verify

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: gh-pages

#after_success: |
#  if [ -n "$GITHUB_TOKEN" ]; then
#    cd "$TRAVIS_BUILD_DIR"
#    # This generates a `web` directory containing the website.
#    make web
#    cd web
#    git init
#    git checkout -b gh-pages
#    git add .
#    git -c user.name='travis' -c user.email='travis' commit -m init
#    # Make sure to make the output quiet, or else the API token will leak!
#    # This works because the API key can replace your password.
#    git push -f -q https://awadodeh:$GITHUB_TOKEN@github.com/awadodeh/group-up-gh-pages gh-pages &2>/dev/null
#    cd "$TRAVIS_BUILD_DIR"
#  fi
